# Generated by Django 6.0 on 2026-04-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='tittle',
        ),
        migrations.AddField(
            model_name='todo',
            name='title',
            field=models.CharField(default='defauit', max_length=200),
            preserve_default=False,
        ),
    ]
